spring:
  datasource:
    url: jdbc:h2:mem:search-place
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

feign:
  hystrix.enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  endpoint:
    kakao-developers:
      name: kakao-developers
      host: https://dapi.kakao.com
      auth-key: ENC(r+7g+Owpu45rDP/ma/btXCoMkuDddErlJST5FOLRc08LO7FpO2PIZgo/uMuNyw0jAzTDuH5wp80=)
    naver-developers:
      name: naver-developers
      host: https://openapi.naver.com
      client-id: ENC(hLuUYsPP9UzEOgkcti/j+quqKJVGB8n8nKQz7vibB6E=)
      client-secret: ENC(zLQEv0aDqveOXfUnS0o0BIM8MDNpkOfG)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor